export const dateRangeOptions = {
  Week: "Week",
  Month: "Month",
  "2 Months": "2 Months",
  "3 Months": "3 Months",
  "6 Months": "6 Months",
  "All Dates": "All Dates",
  "Select Dates": "Select Dates",
}

export const categoryOptions = {
  "All Categories": {
    "All Categories": "All Categories",
  },
  "Major Categories": {
    "Food/Meals": "Food/Meals",
    Housing: "Housing",
    "COVID-19 Control": "COVID-19 Control",
    "Individual, Family and Community Support":
      "Individual, Family and Community Support",
    "Utility Assistance": "Utility Assistance",
    "Disaster Services": "Disaster Services",
    "Information Services": "Information Services",
    "COVID-19 Diagnostic Tests": "COVID-19 Diagnostic Tests",
  },
  "Minor Categories": {
    "Health Care": "Health Care",
    "Other Government/Economic Services": "Other Government/Economic Services",
    Employment: "Employment",
    "Legal, Consumer, and Public Safety Services":
      "Legal, Consumer, and Public Safety Services",
    "Income Support/Assistance": "Income Support/Assistance",
    "Clothing/Personal/Household Needs": "Clothing/Personal/Household Needs",
    "Mental Health/Addictions": "Mental Health/Addictions",
    Transportation: "Transportation",
    "Volunteers/Donations": "Volunteers/Donations",
    Education: "Education",
  },
}
export const areaOptions = {
  "All Areas": "All Areas",
  Barrington: "Barrington",
  Bristol: "Bristol",
  Burrillville: "Burrillville",
  "Central Falls": "Central Falls",
  Charlestown: "Charlestown",
  Coventry: "Coventry",
  Cranston: "Cranston",
  Cumberland: "Cumberland",
  "East Greenwich": "East Greenwich",
  "East Providence": "East Providence",
  Exeter: "Exeter",
  Foster: "Foster",
  Glocester: "Glocester",
  Hopkinton: "Hopkinton",
  Jamestown: "Jamestown",
  Johnston: "Johnston",
  Lincoln: "Lincoln",
  "Little Compton": "Little Compton",
  Middletown: "Middletown",
  Narragansett: "Narragansett",
  Newport: "Newport",
  "New Shoreham": "New Shoreham",
  "North Kingstown": "North Kingstown",
  "North Providence": "North Providence",
  "North Smithfield": "North Smithfield",
  Pawtucket: "Pawtucket",
  Portsmouth: "Portsmouth",
  Providence: "Providence",
  Richmond: "Richmond",
  Scituate: "Scituate",
  Smithfield: "Smithfield",
  "South Kingstown": "South Kingstown",
  Tiverton: "Tiverton",
  Warren: "Warren",
  Warwick: "Warwick",
  Westerly: "Westerly",
  "West Greenwich": "West Greenwich",
  "West Warwick": "West Warwick",
  Woonsocket: "Woonsocket",
}
